import { createFileRoute } from "@tanstack/react-router";

// Rank Math-inspired XSL stylesheet for human-readable sitemaps
const xsl = `<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="2.0"
  xmlns:html="http://www.w3.org/TR/REC-html40"
  xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9"
  xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
<xsl:output method="html" version="1.0" encoding="UTF-8" indent="yes"/>
<xsl:template match="/">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <title>XML Sitemap — HotelAngers.com</title>
  <style>
    body{font:14px/1.5 -apple-system,Segoe UI,Helvetica,Arial,sans-serif;color:#1a1a1a;background:#f7f5f0;margin:0;padding:40px 20px;}
    .wrap{max-width:980px;margin:0 auto;background:#fff;border:1px solid #e5e5e5;}
    header{padding:24px 28px;border-bottom:1px solid #e5e5e5;}
    h1{font:300 28px/1.2 Georgia,serif;margin:0 0 6px;}
    .meta{color:#666;font-size:13px;}
    table{width:100%;border-collapse:collapse;}
    th,td{padding:12px 16px;text-align:left;border-bottom:1px solid #eee;font-size:13px;}
    th{background:#1a1a1a;color:#fff;font-weight:500;text-transform:uppercase;letter-spacing:.08em;font-size:11px;}
    tr:hover{background:#fafafa;}
    a{color:#8b6f47;text-decoration:none;}
    a:hover{text-decoration:underline;}
  </style>
</head>
<body>
  <div class="wrap">
    <header>
      <h1>XML Sitemap</h1>
      <p class="meta">Generated by HotelAngers.com — Guide éditorial des meilleurs hôtels d'Angers.</p>
      <p class="meta"><xsl:value-of select="count(sitemap:sitemapindex/sitemap:sitemap) + count(sitemap:urlset/sitemap:url)"/> URLs</p>
    </header>
    <xsl:if test="sitemap:sitemapindex">
      <table>
        <tr><th>Sitemap</th><th>Last Modified</th></tr>
        <xsl:for-each select="sitemap:sitemapindex/sitemap:sitemap">
          <tr>
            <td><a href="{sitemap:loc}"><xsl:value-of select="sitemap:loc"/></a></td>
            <td><xsl:value-of select="sitemap:lastmod"/></td>
          </tr>
        </xsl:for-each>
      </table>
    </xsl:if>
    <xsl:if test="sitemap:urlset">
      <table>
        <tr><th>URL</th><th>Priority</th><th>Change Freq.</th><th>Last Modified</th></tr>
        <xsl:for-each select="sitemap:urlset/sitemap:url">
          <tr>
            <td><a href="{sitemap:loc}"><xsl:value-of select="sitemap:loc"/></a></td>
            <td><xsl:value-of select="sitemap:priority"/></td>
            <td><xsl:value-of select="sitemap:changefreq"/></td>
            <td><xsl:value-of select="sitemap:lastmod"/></td>
          </tr>
        </xsl:for-each>
      </table>
    </xsl:if>
  </div>
</body>
</html>
</xsl:template>
</xsl:stylesheet>`;

export const Route = createFileRoute("/sitemap.xsl")({
  server: {
    handlers: {
      GET: () =>
        new Response(xsl, {
          headers: {
            "Content-Type": "application/xslt+xml; charset=utf-8",
            "Cache-Control": "public, max-age=86400",
          },
        }),
    },
  },
});
